= DISID Blog

Blog articles written by the DISID Team. Come Learn and Share.

DISID's blog pages are based on Jekyll with GitHub Pages.

The articles are written in AsciiDoc, generated by the https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll AsciiDoc Quickstart] plugin and deployed on Github Pages.

You can use Git command-line to write, commit, and automatically publish blog posts.

If you're just getting started, then follow the directions immediately below. It's actually pretty easy. 


== Repository Structure

The repository requires the following structure to work correctly:

* **master**, for markup sources and blog configuration.
* **gh-pages**, for the generated static content produced by Travis CI with Jekyll AsciiDoc Quickstart plugin.



== Contributing


=== Create and clone the master branch 

From within your DISID blog directory, create and clone the master branch

    git clone https://github.com/DISID/disid-blog

=== Adding a new post

To add a new post, simply navigate to the *_drafts/* directory and create a new file with this structure `YYYY-MM-DD-Title-Of-Your-New-Post.adoc`. 

If you fail to name the file in this structure, Jekyll will ignore that post in the final compilation. 

Open up your newly created file, and fill out the Front matter YAML. This enables Jekyll to properly recognize the post and get essential information regarding the post, like its categories and tags. 


==== Edit the YAML front matter

DISID blog theme uses variable post templates for articles, quotation, video, photo and status updates.

The lines in between the triple dashes (—) provide the essential information about that post to the markdown/textile parser during Jekyll compilation.    

Open up the post in your favorite text editor. 

Edit the URLs and other values in the YAML front matter as appropriate. This should be self-explanatory.

A new blog post should have the following structure to utilise the themes functions:

[source,yaml]
----

---
layout: post
type:  photo                    # ! Important if you want to show a thumbnail on home page
photo: some-image.jpg           # In case you do not want the featured image to display on the front page
title: "Some Title"             # Title of the post
description: Some description   # Description of the post, used for Facebook Opengraph & Twitter
headline: Some headline         # Will appear in bold letters on top of the post
modified: YYYY-MM-DD            # Date
category: how-to
tags: []
image:
  feature: some-image.jpg
---
Content goes here
----


==== Adding images on post

The theme supports for large feature images that span the full-width of the screen, and is meant for text heavy blog posts (or articles).

A good rule of thumb is to keep feature images nice and wide. An image cropped around around 1024 x 768 pixels will keep file size down with an acceptable resolution for most devices. If you want to serve these images responsively I'd suggest looking at https://github.com/scottjehl/picturefill[Picturefill] or http://adaptive-images.com/[Adaptive Images].

The layout make the assumption that the feature images live in the *images* folder. To add a feature image to a post just include the filename in the front matter like so.

[source,yaml]
----
image:
  feature: feature-image-filename.jpg
  thumb: thumbnail-image.jpg #keep it square 200x200 px is good
----


==== Adding author on post

DISID blog posts embeds a corporative signature after the main content block.

To add your signature on a post, make sure your post contains the following contents and customizes with your data in your post's Front Matter YAML:

[source,yaml]
----
author:
    name: Your Name
    image: profile picture URL
    jobdescription: Job Description
    twitter: @twitter-profile
----


==== Check out the sample posts

Check out the sample posts in `_posts` to see examples for quotation posts, status posts, pulling in feature images wrap, assigning categories and tags, and other YAML data

You can see the list of sample posts at http://disid.github.io/disid-blog/samples[Samples page].

This sample posts are posts customized as 

[source,yaml]
----
category: Sample
tags: [sample]
samples: true
----

This values let us publish hidden posts and lets you see sample posts in Github Pages.


=== Commit your post

After you’ve added one or few posts and Once you're satisified with your edits, commit your changes and push the `master` up to `origin` remote.

    git commit -m "Added my post"
    git push origin master
    git push


Your post will be added at `_drafts` folder and it's not published yet.


===  View your post live on the web

All you have to do is add your post at `_drafts` folder, and our team of content curators will review and pick up your content and it will be move it to `_posts` folder.

Joining our content team is simple and easy. We will review your post content and respond as soon as possible.

After that, you should be able to see your post at http://blog.disid.com/


== View the site locally

Assuming you're already within your disid-blog clone directory, and you've already checked out the `master` branch, follow these simple directions to view your site locally:

### Install http://jekyllrb.com[Jekyll] if you have not already

    gem install bundler
    bundle

### Run jekyll

Use the `--watch` flag to pick up changes to files as you make them, allowing you a nice edit-and-refresh workflow.

    bundle exec jekyll serve --watch

Use the `--drafts` flag to show drafts posts at `_drafts` folder not published yet.

    bundle exec jekyll serve --drafts

> *Important:* Because the `url` is set explicitly within `_config.yml` file, you'll need to fully-qualify the URL to view your pages. Vhen running Jekyll locally will be <http://localhost:4000/>. 


== Thanks to 

* The https://github.com/asciidoctor/jekyll-asciidoc-quickstart[Jekyll AsciiDoc Quickstart] is a leg-up in starting your own website hosted on Github with content based in AsciiDoc.

* HMFAYSAL OMEGA is a minimalist, beautiful, responsive theme for Jekyll designed for engineers as well as writers who want their content to take front and center. HMFAYSAL OMEGA is the most complete and complex theme designed for Jekyll to date, ready to handle whatever you throw at it. It was built – by Engineer slash Mathematician http://www.hossainmohdfaysal.com/[Hossain Mohd Faysal].



== License

Copyright (C) 2013 [DISID CORPORATION S.L.](http://www.disid.com/en/)

This work is licensed under the terms of the GNU General Public License as published by the Free Software Foundation, version 3 of the License.

This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

To view a copy of this license, visit http://www.gnu.org/copyleft/gpl.html


== Stay tuned

Follow our articles on official blog http://blog.disid.com.

Contact us?

If you use Twitter, you are encouraged to follow http://twitter.com/disid_corp[@disid_corp] and we appreciate your mentions.